server {
    
    listen 443 ssl;
    listen 80;
    server_name lpalabos.42.fr;

    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    location ~ \.php$ {
    # 1. On vérifie que le fichier existe, sinon erreur 404
    try_files $uri $uri/ /index.php?$args;

    # 2. On passe la requête au conteneur wordpress sur le port 9000
    fastcgi_pass wordpress:9000;

    # 3. On indique le fichier index par défaut pour PHP
    include snippets/fastcgi-php.conf;

    # 4. Paramètres standards requis pour que PHP-FPM comprenne la requête
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}