user			www-data;
include 		/etc/nginx/modules-enabled/*.conf;

worker_processes    	auto; #automatically defines the number of worker processes
worker_rlimit_nofile 	1024; #sets the limit of open files used by worker processes

events {
}

http {
	include		/etc/nginx/mime.types; #tells the browser the intended data format
	default_type	application/octet-stream; #backup in case the data format isnt in the mime.types

	sendfile	on; #doenst copy the file into a buffer before sending it
	tcp_nopush	on; #sends the headers and the data in the same packet

	server_tokens	off; #disables emitting nginx version on error pages and in the “Server” response header field 
	add_header	X-Content-Type-Options nosniff; #prevents MIME sniffing
	add_header	X-Frame-Options SAMEORIGIN; #prevents clickjacking attacks
	add_header	Strict-Transport-Security "max-age=31536000; includeSubDomains" always; #prevent MITM attacks when upgrading from HTTP to HTTPS connection
	
	gzip		on; #for file compression

	access_log 	/var/log/nginx/access.log;

	include 	/etc/nginx/conf.d/*.conf;
	include 	/etc/nginx/sites-enabled/*;

	index	 	index.php index.html index.htm; 

	upstream wordpress {
		zone			wordpress 32K; #creates a shared memory area for worker processes to share backend server state info
		server			wordpress:9000; #server handling proxied requests
		keepalive		2; #enables caching of connections
	}
}