services:
 mariadb:
  container_name: mariadb
  networks:
    - inception
  build:
    context: requirements/mariadb
    dockerfile: dockerfile
  env_file: .env
  restart: on-failure
  volumes:
   - mariadb:/var/lib/mysql
  expose:
   - "3306"
 wordpress:
  container_name: wordpress
  networks:
    - inception
  build:
    context: requirements/wordpress
    dockerfile: dockerfile
  restart: on-failure
  env_file: .env
  depends_on:
   - mariadb
  volumes:
   - wordpress:/var/www/html
  expose:
    - "9000"
 nginx:
  container_name: nginx
  networks:
    - inception
  build:
    context: requirements/nginx
    dockerfile: dockerfile
  restart: on-failure
  env_file: .env
  ports:
   - "443:443"

volumes:
 wordpress:
  driver: 'local'
  driver_opts:
   type: 'none' 
   o: 'bind'	
   device: '/home/lpalabos/data/wordpress'
 mariadb:
  driver: 'local'
  driver_opts:
   type: 'none' 
   o: 'bind'	
   device: '/home/lpalabos/data/mariadb'
networks:
  inception:
   driver: bridge