ARG base=debian

ARG version=bookworm

FROM $base:$version

RUN apt update && apt install -y \
    mariadb-client \
    mariadb-server \
    galera-4 \
    && rm -rf /var/lib/apt/lists/*
    
COPY conf/mysqld.cnf	/etc/mysql/mariadb.conf.d/mysqld.cnf

COPY tools/configure.sh /usr/local/bin/configure.sh

RUN chmod +x /usr/local/bin/configure.sh
RUN mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld

EXPOSE 3306

ENTRYPOINT [ "/usr/local/bin/configure.sh" ]
